#!/usr/bin/env python3
"""Generate fixtures + case list for the Icarus smoke test (tb_smoke.sv).

Emits, under fixtures/:  caseN_msg.hex / caseN_exp.hex ($readmemh, one byte
per line), and smoke_cases.svh with the run_case() sequence the TB includes.

Golden reference is Python hashlib (SHA-3/SHAKE) — the same primitive the
software layers wrap and the NIST KATs exercise.

Run from hardware/tb/smoke/:  python3 gen_smoke.py
"""

import hashlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "fixtures")

# mode enum ints must match keccak_pkg::keccak_mode_e.
SHAKE128, SHAKE256, SHA3_256, SHA3_512 = 0, 1, 2, 3


def _pat(n: int) -> bytes:
    return bytes((i * 37 + 11) & 0xFF for i in range(n))


def _digest(mode: int, msg: bytes, out_len: int) -> bytes:
    if mode == SHAKE128:
        return hashlib.shake_128(msg).digest(out_len)
    if mode == SHAKE256:
        return hashlib.shake_256(msg).digest(out_len)
    if mode == SHA3_256:
        return hashlib.sha3_256(msg).digest()
    return hashlib.sha3_512(msg).digest()


# (mode, message, out_len, label). Chosen to cover: single-block absorb+squeeze
# (empty msgs, all 4 modes), multi-block absorb (200 B > rate), and multi-block
# squeeze (out_len > rate for SHAKE256, rate=136).
CASES = [
    (SHAKE256, b"",        32,  "shake256(empty) 32B"),
    (SHAKE128, b"",        32,  "shake128(empty) 32B"),
    (SHA3_256, b"",        32,  "sha3_256(empty) 32B"),
    (SHA3_512, b"",        64,  "sha3_512(empty) 64B"),
    (SHAKE256, _pat(200),  32,  "shake256(pat200) 32B  [multi-block absorb]"),
    (SHAKE256, b"",        168, "shake256(empty) 168B  [multi-block squeeze]"),
    (SHAKE256, _pat(200),  300, "shake256(pat200) 300B [absorb+squeeze]"),
]


def _write_hex(path: str, data: bytes) -> None:
    with open(path, "w") as f:
        f.write("".join(f"{b:02x}\n" for b in data))


def main() -> None:
    os.makedirs(FIX, exist_ok=True)
    lines = ["// AUTO-GENERATED by gen_smoke.py — do not edit.",
             "// Included inside tb_smoke's initial block; fills msg/exp then runs."]
    for i, (mode, msg, out_len, label) in enumerate(CASES):
        exp = _digest(mode, msg, out_len)
        _write_hex(os.path.join(FIX, f"case{i}_exp.hex"), exp)
        if msg:
            _write_hex(os.path.join(FIX, f"case{i}_msg.hex"), msg)
            lines.append(f'$readmemh("fixtures/case{i}_msg.hex", msg);')
        lines.append(f'$readmemh("fixtures/case{i}_exp.hex", exp);')
        lines.append(
            f'run_case({mode}, {len(msg)}, {out_len}, "{label}");')
    with open(os.path.join(HERE, "smoke_cases.svh"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(CASES)} cases -> fixtures/ + smoke_cases.svh")


if __name__ == "__main__":
    main()
