#!/usr/bin/env python3
"""Generate golden Keccak/SHAKE/SHA3 vectors for the UVM scoreboard.

The reference is Python's `hashlib`, which is the same primitive the
software layers (mlkem/hashes.py, mldsa/hashes.py, slhdsa/hashes.py) wrap
and that the NIST KATs already exercise transitively. We emit one file per
DUT mode; the UVM `keccak_kat_sequence` replays them.

File format (one record per line, `#` comments ignored):

    <msg_hex>:<out_len>:<expected_digest_hex>

`msg_hex` may be empty (empty message). `out_len` is in bytes.

Run:  python3 gen_vectors.py        # writes *.vec next to this script
"""

import hashlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Messages chosen to stress absorb boundaries: empty, short, one full rate
# block minus/plus a byte, and multi-block. Lengths in bytes.
_MSG_LENS = [0, 1, 32, 71, 72, 135, 136, 167, 168, 200, 400]


def _msg(nbytes: int) -> bytes:
    # Deterministic, position-dependent pattern (no RNG -> reproducible).
    return bytes((i * 37 + 11) & 0xFF for i in range(nbytes))


# mode name -> (hashlib factory, is_xof, fixed_or_default_out_len)
_MODES = {
    "shake128": (hashlib.shake_128, True, 32),
    "shake256": (hashlib.shake_256, True, 32),
    "sha3_256": (hashlib.sha3_256, False, 32),
    "sha3_512": (hashlib.sha3_512, False, 64),
}

# Extra output lengths to exercise the XOF squeeze path (multi-block output).
_XOF_OUT_LENS = [1, 32, 168, 300]


def _digest(factory, is_xof, msg: bytes, out_len: int) -> bytes:
    h = factory(msg)
    return h.digest(out_len) if is_xof else h.digest()


def main() -> None:
    for name, (factory, is_xof, default_len) in _MODES.items():
        path = os.path.join(HERE, f"{name}.vec")
        lines = [f"# golden vectors for {name} (generated by gen_vectors.py)"]
        for nbytes in _MSG_LENS:
            msg = _msg(nbytes)
            out_lens = _XOF_OUT_LENS if is_xof else [default_len]
            for out_len in out_lens:
                dig = _digest(factory, is_xof, msg, out_len)
                lines.append(f"{msg.hex()}:{out_len}:{dig.hex()}")
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"wrote {path} ({len(lines) - 1} vectors)")


if __name__ == "__main__":
    main()
